### PR TITLE
[DEV-4476] Update question page sidebar component to new design

### PR DESCRIPTION
**Pull request by empanda**
https://roverdotcom.atlassian.net/browse/DEV-4476

### CODE REVIEW

**Comment by empanda** [comment]
@mwhansen please review and +1. Thanks.

**Comment by empanda** [comment]
https://roverdotcom.atlassian.net/secure/attachment/16770/Screen+Shot+2015-07-01+at+2.47.59+PM.png

**Comment by mwhansen** [comment]
How hard would it be to get tooltips over the three icons?  It's not immediately obvious to me what they mean.

**Comment by empanda** [comment]
Good point, I'll add tooltips.

**Comment by empanda** [comment]
@mwhansen I've added the tooltips.

**Comment by mwhansen** [comment]
:+1:

**Pull request merged**
