### PR TITLE
[DEV-6911] reduce sass friction with pre-compiled css

### PR DESCRIPTION
**Pull request by jmptr**

### CODE REVIEW

**Comment by jmptr** [comment]
@empanda this PR move all the sass parts of askrover into the web project, allowing us to quickly reduce the dependency between askrover and the web project (for styles).  Please review and :+1:!

**Comment by philipkimmey** [comment]
@jmptr I just chatted w/ Johann about this one - it seems like a better approach would be just to build that askbot.css and host is totally separately like in an S3 bucket.

**Comment by philipkimmey** [comment]
@empanda Can you take a look at this one & make sure you're cool w/ it?

I've :+1: 'ed the web side of this one.

**Comment by philipkimmey** [comment]
I'm :+1: on this - let's :shipit: !

**Pull request merged**
