### PR TITLE
Freeze Coffin version to <2.0

### PR DESCRIPTION
**Pull request by delinhabit**
@jthigpen Please PR and :+1:

### CODE REVIEW

**Comment by jthigpen** [comment]
:+1:

Does askbot have an automated test suite we should be running?

**Comment by delinhabit** [comment]
I don't know :)

@mwhansen or @empanda can you help me with this? Does askbot have an automated test suite we should be running?

**Comment by jthigpen** [comment]
I don't think it matters today, but I was just wondering. If we're keeping this thing around we should probably get that running someday.

**Comment by delinhabit** [comment]
@jthigpen Agree

**Pull request merged**
