### PR TITLE
[DEV-4972] Reinstate timestamp on question summary

### PR DESCRIPTION
**Pull request by professorplumb**
https://roverdotcom.atlassian.net/browse/DEV-4972

### CODE REVIEW

**Comment by professorplumb** [comment]
@empanda please review and +1

**Comment by empanda** [comment]
:+1: looks good

**Comment by empanda** [comment]
@professorplumb I'll take care of the merge dance to get this deployed.

**Comment by professorplumb** [comment]
Thanks!

**Pull request merged**
