### PR TITLE
[DEV-4469] Update horizontal voting component to new design

### PR DESCRIPTION
**Pull request by empanda**
https://roverdotcom.atlassian.net/browse/DEV-4469

### CODE REVIEW

**Comment by empanda** [comment]
@mwhansen please review and +1. Thanks.

**Comment by empanda** [comment]
I decided to make all of these changes using just CSS and not editing any of the HTML because the HTML fragments are cached in memcached and I didn't want to go through and try to invalidate the entire cache.

**Comment by mwhansen** [comment]
It looks like the text within the buttons should be "text-align: center;"  as it looks a bit of left-aligned.  Also, I think we should get rid of the margin-top on the question title h2.

**Comment by empanda** [comment]
I decided to center align the text inside the buttons because then the icons don't line up down the page. It looked better when they lined up.

**Comment by empanda** [comment]
@mwhansen I've updated the h2 question links to be level with the count boxes.

**Comment by mwhansen** [comment]
You mean you decided to left-align them?

**Comment by empanda** [comment]
Yes sorry. They're left aligned so that the icons line up vertically on the page.

**Comment by mwhansen** [comment]
How about adding something like

```
    display: inline-block;
    width: calc(100% - 35px);
    text-align: center;
```
to the span.item-count and removing the margin-right:5px from the icon?

**Comment by empanda** [comment]
I'll try that.

**Comment by empanda** [comment]
@mwhansen Updated with your suggestion.

**Comment by mwhansen** [comment]
:+1: looks good

**Pull request merged**
