### PR TITLE
[DEV-4472] Update main page sidebar component to new design

### PR DESCRIPTION
**Pull request by empanda**
https://roverdotcom.atlassian.net/browse/DEV-4472

### CODE REVIEW

**Comment by empanda** [comment]
@mwhansen please review and +1. Thanks.

**Comment by empanda** [comment]
True diff https://github.com/roverdotcom/askbot-devel/compare/DEV-4479...DEV-4472.

**Comment by mwhansen** [comment]
:+1:

It seems to be coming along nicely now.

**Comment by empanda** [comment]
Yeah things are falling into place better than I thought they would.

Thanks for doing all these reviews.

**Pull request merged**
