### PR TITLE
[DEV-89953] Remove mark as correct answer functionality

### PR DESCRIPTION
**Pull request by ramironieto**
# What is the reason for this pull request?
Removes mark as correct answer functionality.

# Deployment
## How can I tell if this change has been deployed?
- You can no longer see the icon to mark an answer as correct.

# Code Review Instructions

## Acceptance tests
- [ ] Answers that are already marked as correct still show
- [ ] Answers that are not marked as correct no longer show an icon

Screenshot 2023-04-17 at 16 23 57

### CODE REVIEW

**Comment by deeBarber** [comment]
It looks like the checkmark is no longer centered since we added the "score" text. Can we add a couple px of padding to get it closer to center?

**Comment by deeBarber** [comment]
I think we should remove the green hover color, since it's no longer interactive.

**Comment by ramironieto** [comment]
> I think we should remove the green hover color, since it's no longer interactive.

It's always green, not only on hover

**Comment by ramironieto** [comment]
"centered": 
Screenshot 2023-04-18 at 15 18 50

**Review by delinhabit — APPROVED** [review]
👍

**Comment by deeBarber** [comment]
> 

https://user-images.githubusercontent.com/94873969/232874699-b8c7b138-21a9-47d6-bc5f-9aa7393abb01.mov

Is that something we changed? On prod it's grey until you hover

**Comment by ramironieto** [comment]
> > 
> 
>  Screen.Recording.2023-04-18.at.11.47.47.AM.mov 
> Is that something we changed? On prod it's grey until you hover

This PR removes the grey checkmarks altogether, now there only is a green checkmark when the answer was previously selected as correct. Note that the other answer in the PR's image doesn't have a grey checkmark.

**Pull request merged**
