### PR TITLE
[DEV-89874] Fix broken tests

### PR DESCRIPTION
**Pull request by GenaroNadile**
Fixes or removes the tests that were failing

### CODE REVIEW

**Review by drschrod — COMMENTED** [review]
Are the tests that are being removed related to functionality that is no longer in the code? How can I tell if the proper tests were removed vs tests that should be updated/fixed?

**Comment by GenaroNadile** [comment]
> Are

Sorry I forgot to write it in the description, the tests that needed to be fixed were the ones that accessed the page /users and /faq, this two urls were removed and that is why I removed those lines of code

**Comment by GenaroNadile** [comment]
> Are the tests that are being removed related to functionality that is no longer in the code? How can I tell if the proper tests were removed vs tests that should be updated/fixed?

you can check the tests pass here [https://github.com/roverdotcom/askrover/pull/145](https://github.com/roverdotcom/askrover/pull/145)

**Comment by drschrod** [comment]
> > Are
> 
> Sorry I forgot to write it in the description, the tests that needed to be fixed were the ones that accessed the page /users and /faq, this two urls were removed and that is why I removed those lines of code

Can you update the description with this information

**Review by jacksonfoster4-rover — APPROVED** [review]

**Pull request merged**
