### PR TITLE
[DEV-4479] Update answer list component to new design

### PR DESCRIPTION
**Pull request by empanda**
https://roverdotcom.atlassian.net/browse/DEV-4479

### CODE REVIEW

**Comment by empanda** [comment]
True diff https://github.com/roverdotcom/askbot-devel/compare/DEV-4474...DEV-4479.

**Comment by empanda** [comment]
@mwhansen please review and +1. Thanks.

**Comment by empanda** [comment]
https://roverdotcom.atlassian.net/secure/attachment/16773/Screen+Shot+2015-07-01+at+2.52.56+PM.png

**Comment by mwhansen** [comment]
:+1:

**Pull request merged**
