### PR TITLE
[DEV-4471] Question list new design update

### PR DESCRIPTION
**Pull request by empanda**
https://roverdotcom.atlassian.net/browse/DEV-4471

### CODE REVIEW

**Comment by empanda** [comment]
Here's the true diff https://github.com/roverdotcom/askbot-devel/compare/DEV-4468...DEV-4471.

**Comment by empanda** [comment]
@mwhansen please review and +1. Thanks.

**Comment by mwhansen** [comment]
:+1: assuming that the votes/answers/views will be handled in a subsequent pull request

**Comment by empanda** [comment]
Yep there's a separate ticket for those items, see https://roverdotcom.atlassian.net/browse/DEV-4469.

**Pull request merged**
